### ISSUE TITLE
Deesse problem in s2dcd

### ISSUE THREAD

**Issue by zuozuo12** [randlab/s2Dcd#1]
Dear professor, I am running s2dcd on the windows system and it prompts "SystemExit ERROR: problems in deesseOMP.exe". I want to ask if deesse needs to be installed separately? Looking forward to your reply.Thanks!

solved

**Comment by alecomunian** [comment]
Hi zuozuo12,
Yes, as stated in the documentation the s2Dcd module is only a wrapper and need an external MPS engine to run (like for example the "deesse"). If you need the DeeSse MPS simulation engine, please have a look at the "geone" page ([https://github.com/randlab/geone](url)).
In a next future we are planning to improve the linkage between this package and "geone".
Kind regards
